[package]
name = "sugondat-shim-common-sovereign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
jsonrpsee = { version = "0.20.3", features = ["macros"] }
serde = { version = "1.0.192", features = ["derive"] }
sugondat-nmt = { path = "../../../sugondat-nmt", features = ["serde"] }

[features]
default = ["client", "server"]
client = ["jsonrpsee/ws-client"]
server = ["jsonrpsee/server"]
