[package]
name = "pallet-sugondat-length-fee-adjustment"
version = "0.1.0"
description = "Pallet for fee Adjustment based on block length and weight"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
frame-benchmarking = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-balances = { workspace = true }
sp-io = { workspace = true, optional = true }
sp-runtime = { workspace = true }
sp-weights = { workspace = true }
sp-arithmetic = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true, features = ["parameterized-consensus-hook",] }
polkadot-primitives = { workspace = true }

[dev-dependencies]
sp-io = { workspace = true }
sp-core = { workspace = true }

[features]
default = [ "std" ]
std = [
    "parity-scale-codec/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-weights/std",
    "scale-info/std",
    "sp-arithmetic/std",
    "pallet-transaction-payment/std",
    "pallet-balances/std",
    "cumulus-pallet-parachain-system/std",
    "polkadot-primitives/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"dep:sp-io"
]
try-runtime = [ "frame-support/try-runtime" ]