[package]
name = "pallet-ikura-blobs"
description = "FRAME pallet for submitting blobs"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }

# Substrate
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }

# Local
ikura-primitives = { workspace = true }
ikura-nmt = { workspace = true }

[dev-dependencies]
ikura-nmt = { workspace = true, default-features = true }

# Substrate
sp-core = { workspace = true }
sp-state-machine = { workspace = true }
sp-trie = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"ikura-nmt/native",
    "ikura-primitives/std",
]
try-runtime = [ "frame-support/try-runtime" ]
